groups:
    - groupa
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name


attributes:
    osxdefaults:
        computername: MACC02K817YDRVG
    homebrewalt:
        apps:

        cask_apps:

    git:
        name: Michael Helfer
        email: michael.helfer@bestbuy.com