recipes:                                       # Configs are parsed and every list is appended to each other, chef handles order and de-duplication
    global:                                    # Recipes mentioned under "global" are installed for all operating systems (we used to support linux, and may do so in the future)
        - applications::create_var_chef_cache
        - dotfiles::sshconfig
    mac_os_x:                                  # Recipes mentioned under "mac_os_x" are installed on OSX and OSX Server
        - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::mail_when_searching_do_not_include_trash
attributes:
    homebrewalt:
        apps:
            - git
        cask_apps:
            - google-chrome
            - firefox
            - iterm2
            - java
            - sourcetree
            - sublime-text3
            - evernote
            - google-drive
            - caffeine
    oh_my_zsh:
        theme: robbyrussell
        plugins:
                -gem
                -git
                -sublime
    sublime_text_packages:
        -
            name: SideBarEnhancements
            source: https://github.com/titoBouzout/SideBarEnhancements
            branch: st3
        -
            name: BracketHighlighter
            source: https://github.com/facelessuser/BracketHighlighter.git
            branch: ST3
        -
            name: WordCount
            source: https://github.com/SublimeText/WordCount.git
            branch: st3
        -
            name: SublimePrettyjson
            source: https://github.com/dzhibas/SublimePrettyJson.git
            branch: master
        -
            name: Gist
            source: https://github.com/condemil/Gist
            branch: master
